In [1]:
%load_ext autoreload 
#hopefully this will reload the modules when they are changed specifically when i change the plotting modules
%autoreload 2

Plot distribution of m200
Save the plot data points in txt
Check what's wrong with bootstrap

In [2]:
from myproject.getRedshiftGalaxyGroupData import GalaxyGroupData

In [3]:
# galaxyGroupData = GalaxyGroupData(sim='TNG300-1')
galaxyGroupData = GalaxyGroupData(sim='TNG-Cluster')

http://www.tng-project.org/api/TNG-Cluster
Main high-resolution TNG-Cluster simulation suite (virtual box), with the full fiducial TNG physics model.
hubble: 0.6774


### do it all at once

In [10]:
galaxyGroupData.computeAllData()


previously got all data for 99
running snapshot: 91
http://www.tng-project.org/api/TNG-Cluster
Main high-resolution TNG-Cluster simulation suite (virtual box), with the full fiducial TNG physics model.
hubble: 0.6774
New z: 0.1
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p1/datacatalogs/SubhaloFlag/SubhaloFlag.hdf5
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p1/datacatalogs/MassType/MassType.hdf5
(10883444, 6)
[0. 0. 0. ... 0. 0. 0.]
[698.514   387.97336  89.01196 ...   0.        0.        0.     ]
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p1/datacatalogs/SubhaloGrNr/SubhaloGrNr.hdf5
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p1/datacatalogs/SubhaloPos/SubhaloPos.hdf5
[175063.89 265874.9  450799.97]
[234940.95 356812.03 604986.94]
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p1/datacatalogs/S

### check one by one

In [4]:
# sim='TNG300-1'
sim='TNG-Cluster'
snapshot=99
galaxyGroupData.__init__(sim, snapshot)
print(f"New z: {galaxyGroupData.z}")
galaxyGroupData.getSubhaloData(sim, snapshot)
galaxyGroupData.getGroupData(sim, snapshot)

http://www.tng-project.org/api/TNG-Cluster
Main high-resolution TNG-Cluster simulation suite (virtual box), with the full fiducial TNG physics model.
hubble: 0.6774
New z: 0
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p0/datacatalogs/SubhaloFlag/SubhaloFlag.hdf5
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p0/datacatalogs/MassType/MassType.hdf5
(10378451, 6)
[0. 0. 0. ... 0. 0. 0.]
[794.57477  405.54102   82.549194 ...   0.         0.         0.      ]
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p0/datacatalogs/SubhaloGrNr/SubhaloGrNr.hdf5
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p0/datacatalogs/SubhaloPos/SubhaloPos.hdf5
[175292.47 265234.53 451367.22]
[258772.47 391547.88 666323.06]
doesn't exist: False or False, datafile: /scratch/poulin.al/lopsided/TNG-Cluster/z0p0/datacatalogs/SubhaloHalfmassRad/SubhaloHalfmassRad.hdf5
doesn'

(array([1.9372881e+15, 1.1157298e+14, 1.2589290e+14, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00], shape=(19453039,), dtype=float32),
 array([2628.561 , 1015.1113, 1056.8062, ...,    0.    ,    0.    ,
           0.    ], shape=(19453039,), dtype=float32),
 array([[258157.11, 389398.84, 667344.6 ],
        [257508.8 , 388557.03, 679791.4 ],
        [265235.03, 399324.8 , 662481.9 ],
        ...,
        [646474.25, 929151.44, 970902.  ],
        [647447.44, 928247.75, 967743.56],
        [647880.8 , 928833.06, 967010.06]],
       shape=(19453039, 3), dtype=float32),
 array([[258772.47, 391547.88, 666323.06],
        [256954.34, 388975.28, 679820.25],
        [265336.5 , 398945.84, 662637.2 ],
        ...,
        [646474.25, 929151.44, 970902.  ],
        [647447.44, 928247.75, 967743.56],
        [647880.8 , 928833.06, 967010.06]],
       shape=(19453039, 3), dtype=float32),
 array([1, 0, 0, ..., 0, 0, 0], shape=(19453039,), dtype=int32),
 {0,
  252455,
  476245,
  692426

In [5]:
galaxyGroupData.getListGalaxyGroup()

headerInformation:
dict_items([('simulation', 'TNG-Cluster'), ('description', 'Main high-resolution TNG-Cluster simulation suite (virtual box), with the full fiducial TNG physics model.'), ('boxsize_kpc', 1003838.2049010925), ('hubble_param', 0.6774), ('redshift', 0), ('scale_factor', 1.0), ('important filters', 'minGGMass=1e13, satWithinR200, M_r_max = -15')])
num subhalos: 10378451
rough number of galaxygroups: 7213184
Processing primary subhalos: 1604166/1604166 (100.0%)
Constructed ListGalaxyGroup with 352 galaxy groups.
 Average satellites: 4527.997159090909


In [6]:
galaxyGroupData.correctTheData()

WARNING.... double check: Correcting positions with boxsize: 1003838.2049010925
Correcting positions in parallel with 27 processes...
Progress: 352/352 (100.0%)
After correcting, ListGalaxyGroup has 352 galaxy groups.
 Average satellites: 4527.997159090909
Filtering subhalos in parallel with 27 processes...
Progress: 352/352 (100.0%)
After filtering: 352 galaxy groups retained.
After filtering, ListGalaxyGroup has 352 galaxy groups.
 Average satellites: 274.51420454545456
 Range of satellites: ((50, 903), [626, 903, 537, 798, 315, 514, 728, 709, 707, 624, 565, 468, 687, 725, 648, 565, 574, 638, 652, 637, 415, 626, 578, 639, 487, 621, 653, 485, 586, 509, 639, 511, 383, 464, 530, 214, 432, 481, 417, 524, 244, 390, 467, 432, 462, 547, 146, 542, 502, 527, 188, 524, 522, 416, 341, 473, 553, 455, 406, 390, 436, 426, 353, 355, 454, 443, 327, 225, 356, 485, 305, 397, 543, 266, 336, 369, 423, 406, 311, 441, 432, 362, 387, 361, 404, 342, 366, 323, 373, 402, 446, 329, 423, 391, 335, 427, 316, 378

#### check join time works

In [7]:
from myproject.utilities.iapi_TNG import get

baseUrl = 'http://www.tng-project.org/api/'
# headers = {"api-key":"env{apikey}"}
r=get(baseUrl)
names = [sim['name'] for sim in r['simulations']]
i = names.index(sim)
sim = get( r['simulations'][i]['url'] )
snaps = get( sim['snapshots'] )

In [8]:
from myproject.utilities.joinTime import JoinTime
import os

rewrite=False

join_times_path = galaxyGroupData.scratchPlotDirc + f'/join_times_and_parameter_changes_{galaxyGroupData.sim}_{galaxyGroupData.snapshot_dic[galaxyGroupData.snapshot][1]}.txt'
satellites_without_tree_path = galaxyGroupData.scratchPlotDirc + f'/satellites_without_merger_tree_{galaxyGroupData.sim}_{galaxyGroupData.snapshot_dic[galaxyGroupData.snapshot][1]}.txt'

join_times_header = (
    "GalaxyGroupID\tSubhaloID\tNumMembers\tClusterMass\tJoiningRedshift\tSeparationZ0\tSeparationNorm\tDeltaMass\tDeltaTAll\tDeltaTLim\tDeltaMassTotal\tDeltaMassDM\tDeltaMassStars\tDeltaVsq\tJoinSnap\tClosestSnap\tClosestNorm\tClosestZ\tJoinProgSnap\tDeltaL\tSubhaloMassAtJoin\tHostProgID\tLJoin\tL0\tFirst1R200Redshift\tFirst2R200Redshift\tFirst3R200Redshift\n"
)

totalSatellites = sum(gg.getNumSubhalos() for gg in galaxyGroupData.filtered_and_corrected_list_galaxy_groups.getAllGalaxyGroups())
print(f"Total number of satellites to process (including centrals in counts): {totalSatellites}")

processedJoinTimes = []
satelliteToJoinTimeMap: dict[int, JoinTime] = {}

satellitesWihtoutMergerTree: set[int] = set()
#load satellitesWihtoutMergerTree from file if exists
# if rewrite==True:
if os.path.exists(satellites_without_tree_path):
    with open(satellites_without_tree_path, 'r') as f:
        for line in f:
            s = line.strip()
            if not s or s.lower().startswith('satellitesubhaloid'):
                continue
            try:
                satellitesWihtoutMergerTree.add(int(s.split('\t')[0]))
            except Exception:
                continue
    print(f"Loaded {len(satellitesWihtoutMergerTree)} satellites without merger tree from file.")
else:
    print("No existing file for satellites without merger tree found, starting with an empty list.")
    #prep the file with header
    with open(satellites_without_tree_path, 'w') as f:
        f.write("SatelliteSubhaloID\n")

# If not rewriting, resume from existing join-times file when available.
completed_satellite_ids: set[int] = set()
join_file_mode = 'w'
should_write_header = True
if not rewrite and os.path.exists(join_times_path):
    join_file_mode = 'a'
    should_write_header = os.path.getsize(join_times_path) == 0
    try:
        with open(join_times_path, 'r') as f:
            for line in f:
                s = line.strip()
                if not s or s.lower().startswith('galaxygroupid'):
                    continue
                parts = s.split('\t')
                if len(parts) < 2:
                    continue
                try:
                    completed_satellite_ids.add(int(parts[1]))
                except Exception:
                    continue
        print(
            f"Resuming from existing {os.path.basename(join_times_path)}: "
            f"{len(completed_satellite_ids)} satellites already completed."
        )
    except Exception as e:
        print(f"WARNING: Failed to read existing join-times file for resume ({e}); will append anyway.")


tasks: list[tuple] = []
for gg in galaxyGroupData.filtered_and_corrected_list_galaxy_groups.getAllGalaxyGroups():
    gg_id = gg.getGroupID()
    num_members = gg.getNumSubhalos()
    cluster_mass = gg.getMCrit200()
    central_subhalo = gg.getCentralSubhalo()
    if central_subhalo is None:
        continue

    host_id = central_subhalo.getIdx()
    for subhalo in gg.getSatelliteSubhalos():
        sat_id = subhalo.getIdx()
        if sat_id in satellitesWihtoutMergerTree:
            continue
        if sat_id in completed_satellite_ids:
            continue
        tasks.append(
            (
                galaxyGroupData.sim,
                galaxyGroupData.snapshot,
                host_id,
                sat_id,
                galaxyGroupData.sim_boxsize_kpc,
                galaxyGroupData.sim_boxsize_kpc/2,
                galaxyGroupData.scratchDataDirc + '/mergerTree',
                gg_id,
                num_members,
                cluster_mass,
            )
        )



Total number of satellites to process (including centrals in counts): 96629
Loaded 1747 satellites without merger tree from file.
Resuming from existing join_times_and_parameter_changes_TNG-Cluster_z0p0.txt: 94530 satellites already completed.


In [ ]:

sim, snapshot, host_id, sat_id, L, halfbox, fname, gg_id, num_members, cluster_mass = tasks[0]
joinTime = JoinTime(sim, snapshot)
join_time_info = joinTime.computeJoinTimes(hostID=host_id, ID=sat_id, L=L, halfbox=halfbox, fname=fname)
print(join_time_info)

## normal

In [10]:
import numpy as np
galaxyGroupData.satelliteJoinTimeDic : dict[int, tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float]] = galaxyGroupData.get_satellite_join_time(galaxyGroupData.filtered_and_corrected_list_galaxy_groups, parallelize=True, rewrite=False) if snapshot == 99 else np.full(len(galaxyGroupData.flag), np.nan)
print(f"length of satelliteJoinTimeDic: {len(galaxyGroupData.satelliteJoinTimeDic.keys())}, length of flag: {len(galaxyGroupData.flag)}") if snapshot == 99 else None
galaxyGroupData.updateSubhalosWithJoinTimes() if snapshot == 99 else None


Total number of satellites to process (including centrals in counts): 96629
Loaded 1747 satellites without merger tree from file.
Resuming from existing join_times_and_parameter_changes_TNG-Cluster_z0p0.txt: 94530 satellites already completed.
No satellites left to process (resume file already contains all targets).
length of satelliteJoinTimeDic: 94530, length of flag: 10378451


In [11]:
#for snapshot 99, check how many subhalos have non nan joining redshifts compared to nan joining redshifts:
# galaxyAnalysis = listRedshiftGalaxyAnalysis.getGalaxyAnalysisSnapshot(99)
# loaded_list_of_galaxy = galaxyAnalysis.loaded_list_of_galaxy_groups
loaded_list_of_galaxy = galaxyGroupData.filtered_and_corrected_list_galaxy_groups
num_subhalos = np.sum([len(galaxy_group.getSatelliteSubhalos()) for galaxy_group in loaded_list_of_galaxy.getAllGalaxyGroups()])
num_subhalos_nan_joining_redshifts = 0
num_subhalos_non_nan_joining_redshifts = 0
for galaxy_group in loaded_list_of_galaxy.getAllGalaxyGroups():
    for satellite_subhalo in galaxy_group.getSatelliteSubhalos():
        if np.isnan(satellite_subhalo.getJoiningRedshift()):
            num_subhalos_nan_joining_redshifts += 1
            # print(satellite_subhalo.getJoiningRedshift())
        else:
            num_subhalos_non_nan_joining_redshifts += 1
print(f"Snapshot 99: Num subhalos: {num_subhalos}, Num subhalos with nan joining redshifts: {num_subhalos_nan_joining_redshifts}, Num subhalos with non-nan joining redshifts: {num_subhalos_non_nan_joining_redshifts}")
print(f"Snapshot 99: Fraction of subhalos with nan joining redshifts: {num_subhalos_nan_joining_redshifts/num_subhalos}, Fraction of subhalos with non-nan joining redshifts: {num_subhalos_non_nan_joining_redshifts/num_subhalos}")

Snapshot 99: Num subhalos: 96277, Num subhalos with nan joining redshifts: 1756, Num subhalos with non-nan joining redshifts: 94521
Snapshot 99: Fraction of subhalos with nan joining redshifts: 0.018239039438287443, Fraction of subhalos with non-nan joining redshifts: 0.9817609605617126


In [12]:
galaxyGroupData.saveListGalaxyGroup()
# print(f"Finished processing for sim: {sim}, snapshot: {snapshot} of index {i}/{len(galaxyGroupData.snapshot_dic.keys())}")

Serializing galaxy group data in parallel with 27 processes...
Serialization: 352/352 (100.0%)
Writing serialized data to HDF5 file...
Writing: 352/352 (100.0%)
Completed writing 352 galaxy groups to HDF5.
Saved galaxy data to /scratch/poulin.al/lopsided/TNG-Cluster/z0p0/data/galaxy_data_TNG-Cluster_.hdf5
0


# why so many nan for tng -cluster mergertree

In [9]:
#check the satellitesWihtoutMergerTree to see if they truly do not have merger tree data
for satellite_id in satellitesWihtoutMergerTree:
    join_time_info = JoinTime(sim, snapshot).computeJoinTimes(hostID=0, ID=satellite_id, L=galaxyGroupData.sim_boxsize_kpc, halfbox=galaxyGroupData.sim_boxsize_kpc/2, fname=galaxyGroupData.scratchDataDirc + '/mergerTree')
    if join_time_info is not None:
        print(f"Satellite {satellite_id} was previously marked as having no merger tree data, but join time info was found: {join_time_info}")

ValueError: {'name': 'TNG-Cluster', 'description': 'Main high-resolution TNG-Cluster simulation suite (virtual box), with the full fiducial TNG physics model.', 'name_alt': 'L680n8192TNG', 'boxsize': 680000.0, 'z_start': 127.0, 'z_final': 0.0, 'cosmology': 'Planck2015', 'omega_0': 0.3089, 'omega_L': 0.6911, 'omega_B': 0.0486, 'hubble': 0.6774, 'physics_model': 'Fiducial TNG Model', 'has_cooling': True, 'has_starformation': True, 'has_winds': True, 'has_blackholes': True, 'mass_gas': 0.000771495, 'mass_dm': 0.00413211373831018, 'softening_dm_comoving': 2.0, 'softening_stars_comoving': 2.0, 'softening_blackholes_comoving': 4.0, 'softening_gas_comoving': 2.0, 'softening_dm_max_phys': 1.0, 'softening_stars_max_phys': 1.0, 'softening_blackholes_max_phys': 4.0, 'softening_gas_max_phys': 1.0, 'softening_gas_factor': 2.5, 'softening_gas_comoving_min': 0.25, 'num_dm': 549755813888, 'num_tr_mc': 15416383432, 'num_tr_vel': 0, 'longids': False, 'is_uniform': True, 'is_zoom': False, 'is_subbox': False, 'num_files_snapshot': 704, 'num_files_groupcat': 352, 'num_files_rockstar': 0, 'num_files_lhalotree': 60, 'num_files_sublink': 14, 'num_files_ctrees': 0, 'filesize_lhalotree': 655543667148.0, 'filesize_sublink': 1439744182948.0, 'filesize_ctrees': 0.0, 'filesize_ics': 0.0, 'filesize_simulation': 813203480.0, 'has_fof': True, 'has_subfind': True, 'has_rockstar': False, 'has_lhalotree': True, 'has_sublink': True, 'has_ctrees': False, 'permission_required': 64, 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG-Cluster/', 'parent_simulation': [], 'child_simulations': [], 'files': {'lhalotree': 'http://www.tng-project.org/api/TNG-Cluster/files/lhalotree/', 'sublink': 'http://www.tng-project.org/api/TNG-Cluster/files/sublink/', 'offsets': 'http://www.tng-project.org/api/TNG-Cluster/files/offsets/', 'simulation': 'http://www.tng-project.org/api/TNG-Cluster/files/simulation.hdf5', 'stellar_assembly': 'http://www.tng-project.org/api/TNG-Cluster/files/stellar_assembly.hdf5', 'relaxedness': 'http://www.tng-project.org/api/TNG-Cluster/files/relaxedness.hdf5', 'coolcore_criteria': 'http://www.tng-project.org/api/TNG-Cluster/files/coolcore_criteria.hdf5', 'cluster_mergers': 'http://www.tng-project.org/api/TNG-Cluster/files/cluster_mergers.hdf5', 'projections': 'http://www.tng-project.org/api/TNG-Cluster/files/projections/', 'merger_history': 'http://www.tng-project.org/api/TNG-Cluster/files/merger_history/'}, 'checksums': 'http://www.tng-project.org/api/TNG-Cluster/checksums/', 'snapshots': 'http://www.tng-project.org/api/TNG-Cluster/snapshots/'} is not in list