In [1]:
%load_ext autoreload 
#hopefully this will reload the modules when they are changed specifically when i change the plotting modules
%autoreload 2

Plot distribution of m200
Save the plot data points in txt
Check what's wrong with bootstrap

In [2]:
from myproject.getRedshiftGalaxyGroupData import GalaxyGroupData

In [19]:
# galaxyGroupData = GalaxyGroupData(sim='TNG300-1')
galaxyGroupData = GalaxyGroupData(sim='TNG-Cluster')

JSON response: {'simulations': [{'name': 'Illustris-1', 'num_snapshots': 134, 'url': 'http://www.tng-project.org/api/Illustris-1/'}, {'name': 'Illustris-1-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-1-Dark/'}, {'name': 'Illustris-2', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-2/'}, {'name': 'Illustris-2-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-2-Dark/'}, {'name': 'Illustris-3', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-3/'}, {'name': 'Illustris-3-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-3-Dark/'}, {'name': 'TNG100-1', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-1/'}, {'name': 'TNG100-1-Dark', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-1-Dark/'}, {'name': 'TNG100-2', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-2/'}, {'name': 'TNG100-2-Dark', 'num_snapsh

### do it all at once

In [ ]:
galaxyGroupData.computeAllData()


### check one by one

In [21]:
# sim='TNG300-1'
sim='TNG-Cluster'
snapshot=99
galaxyGroupData.__init__(sim, snapshot)
print(f"New z: {galaxyGroupData.z}")
galaxyGroupData.getSubhaloData(sim, snapshot)
galaxyGroupData.getGroupData(sim, snapshot)

JSON response: {'simulations': [{'name': 'Illustris-1', 'num_snapshots': 134, 'url': 'http://www.tng-project.org/api/Illustris-1/'}, {'name': 'Illustris-1-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-1-Dark/'}, {'name': 'Illustris-2', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-2/'}, {'name': 'Illustris-2-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-2-Dark/'}, {'name': 'Illustris-3', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-3/'}, {'name': 'Illustris-3-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-3-Dark/'}, {'name': 'TNG100-1', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-1/'}, {'name': 'TNG100-1-Dark', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-1-Dark/'}, {'name': 'TNG100-2', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-2/'}, {'name': 'TNG100-2-Dark', 'num_snapsh

(array([1.9372881e+15, 1.1157298e+14, 1.2589290e+14, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00], shape=(19453039,), dtype=float32),
 array([2628.561 , 1015.1113, 1056.8062, ...,    0.    ,    0.    ,
           0.    ], shape=(19453039,), dtype=float32),
 array([[258157.11, 389398.84, 667344.6 ],
        [257508.8 , 388557.03, 679791.4 ],
        [265235.03, 399324.8 , 662481.9 ],
        ...,
        [646474.25, 929151.44, 970902.  ],
        [647447.44, 928247.75, 967743.56],
        [647880.8 , 928833.06, 967010.06]],
       shape=(19453039, 3), dtype=float32),
 array([[258772.47, 391547.88, 666323.06],
        [256954.34, 388975.28, 679820.25],
        [265336.5 , 398945.84, 662637.2 ],
        ...,
        [646474.25, 929151.44, 970902.  ],
        [647447.44, 928247.75, 967743.56],
        [647880.8 , 928833.06, 967010.06]],
       shape=(19453039, 3), dtype=float32),
 array([1, 0, 0, ..., 0, 0, 0], shape=(19453039,), dtype=int32),
 {0,
  252455,
  476245,
  692426

In [22]:
galaxyGroupData.getListGalaxyGroup()

headerInformation:
dict_items([('simulation', 'TNG-Cluster'), ('description', 'Main high-resolution TNG-Cluster simulation suite (virtual box), with the full fiducial TNG physics model.'), ('boxsize_kpc', 1003838.2049010925), ('hubble_param', 0.6774), ('redshift', 0), ('scale_factor', 1.0), ('important filters', 'minGGMass=1e13, satWithinR200, M_r_max = -15')])
num subhalos: 10378451


rough number of galaxygroups: 7213184
Processing primary subhalos: 1604166/1604166 (100.0%)
Constructed ListGalaxyGroup with 352 galaxy groups.
 Average satellites: 4527.997159090909


In [23]:
galaxyGroupData.correctTheData()

WARNING.... double check: Correcting positions with boxsize: 1003838.2049010925
Correcting positions in parallel with 27 processes...


Progress: 352/352 (100.0%)
After correcting, ListGalaxyGroup has 352 galaxy groups.
 Average satellites: 4527.997159090909
Filtering subhalos in parallel with 27 processes...
Progress: 352/352 (100.0%)
After filtering: 352 galaxy groups retained.
After filtering, ListGalaxyGroup has 352 galaxy groups.
 Average satellites: 274.51420454545456
 Range of satellites: ((50, 903), [626, 903, 537, 798, 315, 514, 728, 709, 707, 624, 565, 468, 687, 725, 648, 565, 574, 638, 652, 637, 415, 626, 578, 639, 487, 621, 653, 485, 586, 509, 639, 511, 383, 464, 530, 214, 432, 481, 417, 524, 244, 390, 467, 432, 462, 547, 146, 542, 502, 527, 188, 524, 522, 416, 341, 473, 553, 455, 406, 390, 436, 426, 353, 355, 454, 443, 327, 225, 356, 485, 305, 397, 543, 266, 336, 369, 423, 406, 311, 441, 432, 362, 387, 361, 404, 342, 366, 323, 373, 402, 446, 329, 423, 391, 335, 427, 316, 378, 435, 427, 332, 273, 311, 323, 345, 398, 334, 414, 310, 394, 369, 347, 295, 371, 307, 399, 266, 409, 361, 307, 281, 299, 399, 303, 30

#### check join time works

In [24]:
from myproject.utilities.iapi_TNG import get

baseUrl = 'http://www.tng-project.org/api/'
# headers = {"api-key":"env{apikey}"}
r=get(baseUrl)
names = [sim['name'] for sim in r['simulations']]
i = names.index(sim)
sim = get( r['simulations'][i]['url'] )
snaps = get( sim['snapshots'] )

JSON response: {'simulations': [{'name': 'Illustris-1', 'num_snapshots': 134, 'url': 'http://www.tng-project.org/api/Illustris-1/'}, {'name': 'Illustris-1-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-1-Dark/'}, {'name': 'Illustris-2', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-2/'}, {'name': 'Illustris-2-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-2-Dark/'}, {'name': 'Illustris-3', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-3/'}, {'name': 'Illustris-3-Dark', 'num_snapshots': 136, 'url': 'http://www.tng-project.org/api/Illustris-3-Dark/'}, {'name': 'TNG100-1', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-1/'}, {'name': 'TNG100-1-Dark', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-1-Dark/'}, {'name': 'TNG100-2', 'num_snapshots': 100, 'url': 'http://www.tng-project.org/api/TNG100-2/'}, {'name': 'TNG100-2-Dark', 'num_snapsh

In [25]:
from myproject.utilities.joinTime import JoinTime
import os

rewrite=False

join_times_path = galaxyGroupData.scratchPlotDirc + f'/join_times_and_parameter_changes_{galaxyGroupData.sim}_{galaxyGroupData.snapshot_dic[galaxyGroupData.snapshot][1]}.txt'
satellites_without_tree_path = galaxyGroupData.scratchPlotDirc + f'/satellites_without_merger_tree_{galaxyGroupData.sim}_{galaxyGroupData.snapshot_dic[galaxyGroupData.snapshot][1]}.txt'

join_times_header = (
    "GalaxyGroupID\tSubhaloID\tNumMembers\tClusterMass\tJoiningRedshift\tSeparationZ0\tSeparationNorm\tDeltaMass\tDeltaTAll\tDeltaTLim\tDeltaMassTotal\tDeltaMassDM\tDeltaMassStars\tDeltaVsq\tJoinSnap\tClosestSnap\tClosestNorm\tClosestZ\tJoinProgSnap\tDeltaL\tSubhaloMassAtJoin\tHostProgID\tLJoin\tL0\tFirst1R200Redshift\tFirst2R200Redshift\tFirst3R200Redshift\n"
)

totalSatellites = sum(gg.getNumSubhalos() for gg in galaxyGroupData.filtered_and_corrected_list_galaxy_groups.getAllGalaxyGroups())
print(f"Total number of satellites to process (including centrals in counts): {totalSatellites}")

processedJoinTimes = []
satelliteToJoinTimeMap: dict[int, JoinTime] = {}

satellitesWihtoutMergerTree: set[int] = set()
#load satellitesWihtoutMergerTree from file if exists
# if rewrite==True:
if os.path.exists(satellites_without_tree_path):
    with open(satellites_without_tree_path, 'r') as f:
        for line in f:
            s = line.strip()
            if not s or s.lower().startswith('satellitesubhaloid'):
                continue
            try:
                satellitesWihtoutMergerTree.add(int(s.split('\t')[0]))
            except Exception:
                continue
    print(f"Loaded {len(satellitesWihtoutMergerTree)} satellites without merger tree from file.")
else:
    print("No existing file for satellites without merger tree found, starting with an empty list.")
    #prep the file with header
    with open(satellites_without_tree_path, 'w') as f:
        f.write("SatelliteSubhaloID\n")

# If not rewriting, resume from existing join-times file when available.
completed_satellite_ids: set[int] = set()
join_file_mode = 'w'
should_write_header = True
if not rewrite and os.path.exists(join_times_path):
    join_file_mode = 'a'
    should_write_header = os.path.getsize(join_times_path) == 0
    try:
        with open(join_times_path, 'r') as f:
            for line in f:
                s = line.strip()
                if not s or s.lower().startswith('galaxygroupid'):
                    continue
                parts = s.split('\t')
                if len(parts) < 2:
                    continue
                try:
                    completed_satellite_ids.add(int(parts[1]))
                except Exception:
                    continue
        print(
            f"Resuming from existing {os.path.basename(join_times_path)}: "
            f"{len(completed_satellite_ids)} satellites already completed."
        )
    except Exception as e:
        print(f"WARNING: Failed to read existing join-times file for resume ({e}); will append anyway.")


tasks: list[tuple] = []
for gg in galaxyGroupData.filtered_and_corrected_list_galaxy_groups.getAllGalaxyGroups():
    gg_id = gg.getGroupID()
    num_members = gg.getNumSubhalos()
    cluster_mass = gg.getMCrit200()
    central_subhalo = gg.getCentralSubhalo()
    if central_subhalo is None:
        continue

    host_id = central_subhalo.getIdx()
    for subhalo in gg.getSatelliteSubhalos():
        sat_id = subhalo.getIdx()
        if sat_id in satellitesWihtoutMergerTree:
            continue
        if sat_id in completed_satellite_ids:
            continue
        tasks.append(
            (
                galaxyGroupData.sim,
                galaxyGroupData.snapshot,
                host_id,
                sat_id,
                galaxyGroupData.sim_boxsize_kpc,
                galaxyGroupData.sim_boxsize_kpc/2,
                galaxyGroupData.scratchDataDirc + '/mergerTree',
                gg_id,
                num_members,
                cluster_mass,
            )
        )



Total number of satellites to process (including centrals in counts): 96629
Loaded 0 satellites without merger tree from file.
Resuming from existing join_times_and_parameter_changes_TNG-Cluster_z0p0.txt: 0 satellites already completed.


In [ ]:

sim, snapshot, host_id, sat_id, L, halfbox, fname, gg_id, num_members, cluster_mass = tasks[0]
joinTime = JoinTime(sim, snapshot)
join_time_info = joinTime.computeJoinTimes(hostID=host_id, ID=sat_id, L=L, halfbox=halfbox, fname=fname)
print(join_time_info)

In [29]:
import numpy as np
galaxyGroupData.satelliteJoinTimeDic : dict[int, tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float]] = galaxyGroupData.get_satellite_join_time(galaxyGroupData.filtered_and_corrected_list_galaxy_groups, parallelize=True, rewrite=False) if snapshot == 99 else np.full(len(galaxyGroupData.flag), np.nan)
print(f"length of satelliteJoinTimeDic: {len(galaxyGroupData.satelliteJoinTimeDic.keys())}, length of flag: {len(galaxyGroupData.flag)}") if snapshot == 99 else None
galaxyGroupData.updateSubhalosWithJoinTimes() if snapshot == 99 else None


Total number of satellites to process (including centrals in counts): 96629
Loaded 0 satellites without merger tree from file.
Resuming from existing join_times_and_parameter_changes_TNG-Cluster_z0p0.txt: 0 satellites already completed.
Computing join times in parallel: 96277 satellites, 27 processes, chunksize=445
No merger tree for satellite 1440555: 404 Client Error: Not Found for url: https://data-eu.tng-project.org/tree/sublink_mpb/L680n8192TNG/99/1440555/hdf5/?token=d45ec7380422348ba5f8
No merger tree for satellite 1241517: 404 Client Error: Not Found for url: https://data-eu.tng-project.org/tree/sublink_mpb/L680n8192TNG/99/1241517/hdf5/?token=10cb48dc75d7d88d9ead
No merger tree for satellite 140440: 404 Client Error: Not Found for url: https://data-eu.tng-project.org/tree/sublink_mpb/L680n8192TNG/99/140440/hdf5/?token=fe39df3a79784195052f
No merger tree for satellite 1441548: 404 Client Error: Not Found for url: https://data-eu.tng-project.org/tree/sublink_mpb/L680n8192TNG/99/14

In [18]:
galaxyGroupData.saveListGalaxyGroup()
print(f"Finished processing for sim: {sim}, snapshot: {snapshot} of index {i}/{len(galaxyGroupData.snapshot_dic.keys())}")

Serializing galaxy group data in parallel with 27 processes...


Serialization: 3707/3707 (100.0%)
Writing serialized data to HDF5 file...
Writing: 3707/3707 (100.0%)
Completed writing 3707 galaxy groups to HDF5.
Saved galaxy data to /scratch/poulin.al/lopsided/TNG300-1/z0p1/data/galaxy_data_TNG300-1_.hdf5
1
Finished processing for sim: TNG300-1, snapshot: 91 of index 16/11
